version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wgmgr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wgmgr
    volumes:
      - './test/init_sql/:/docker-entrypoint-initdb.d/'
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080